### ISSUE TITLE
Include web/file/s3 file/image reading utilities

### ISSUE THREAD

**Issue by RussTorres** [AllenInstitute/render-python#137]
I think it makes more sense to put here than in render-modules, and would help standardize tile interactions.

**Comment by fcollman** [comment]
agreed.  I thought that maybe we had s3 support already, but maybe that is just in render.  I guess we need it for the client side rendering of transformed tiles.

**Comment by fcollman** [comment]
is there another library that already wraps/owns this that we can use rather than rewriting this stuff from scratch?

**Comment by RussTorres** [comment]
I don't think there is any accepted general purpose way to access non-aws s3 configurations (and Render explicitly does not support mixed s3 sources).  In my projects I've recently been adding query parameters to the uri to describe differences in endpoint and region.

I think building on top of boto3 and botocore is pretty well established and not too many lines of code, but there is still conversation at the institute and beyond about using other kinds of custom object stores (rados, backblaze, etc.) For which we definitely need some unified handling that I haven't seen in a quick survey.
Any suggestions are welcome.

**Comment by RussTorres** [comment]
I have included these via a thin interface to uri-handler in render-modules.  We can substitute this if a better solution comes along, or add it to this repo if reading images becomes required.  For now I am going to close this.
