### ISSUE TITLE
Tilepair client, cannot find json file

### ISSUE THREAD

**Issue by martinschorb** [AllenInstitute/render-python#150]
Dar all,

I am running into a problem when generating tile pairs:

when I try to run it in a 2D layer with
```
"zNeighborDistance":0,
"excludeSameLayerNeighbors":"False",
```

it fails not finding the JSON (which it is supposed to create):

```
  File "/.../renderapi/render.py", line 128, in run
    return f(*args, **kwargs)
  File "<decorator-gen-35>", line 2, in tilePairClient
  File "/.../renderapi/client/utils.py", line 36, in renderclientaccess
    return f(*args, **render.make_kwargs(**kwargs))
  File "/.../renderapi/client/client_calls.py", line 231, in tilePairClient
    with open(outjson, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/.../tile_pairs_giovanna0_mipmap_z_442_to_450_dist_0.json'
```
running the very same parameters but with 

```
  "zNeighborDistance":1,
```

succeeds. On another stack it works with
```
  "zNeighborDistance":0,
```

What would be the relevant stack parameter to check? The directory is writable, as it creates the files with `...1.json`.

**Comment by martinschorb** [comment]
OK, I think I found the issue. There are simply no overlapping/neighboring tiles in the substack I was looking at. So the file was not created.

**Comment by martinschorb** [comment]
It seems this is also an issue when the underlying Java Tilepair client creates multiple files:

https://github.com/AllenInstitute/render-python/blob/7208b41f1bc14bc3f027e8553d8fabcbb2cfc572/renderapi/client/client_calls.py#L231

```
renderapi/client/client_calls.py", line 231, in tilePairClient
    with open(outjson, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '...'
```

**Comment by RussTorres** [comment]
closing with #151.
